# theme: jekyll-theme-minimal
title: Liekkij채rven VPK:n kotisivu
description: Kyseess채 on kuvitteellisen Liekkij채rven VPK:n kotisivu, joka on tehty Jekyllill채 osana Haaga-Helian kurssia Johdanto digitaalisiin palveluihin.