# theme: jekyll-theme-minimal
title: Liekkijärven VPK:n kotisivu
description: Kyseessä on kuvitteellisen Liekkijärven VPK:n kotisivu, joka on tehty osana Haaga-Helian kurssia Johdanto digitaalisiin palveluihin.
